# Generated by Django 5.2.1 on 2025-05-27 01:39

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
    ]
