# Generated by Django 5.2.1 on 2025-05-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
